//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnackHub.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SnackHub.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * O {0} é obrigatório!.
        /// </summary>
        public static string VAL001 {
            get {
                return ResourceManager.GetString("VAL001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * O {0} deve ter no mínimo {2} e máximo {1} caracteres!.
        /// </summary>
        public static string VAL002 {
            get {
                return ResourceManager.GetString("VAL002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * A {0} é obrigatória!.
        /// </summary>
        public static string VAL003 {
            get {
                return ResourceManager.GetString("VAL003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * A confirmação da {0} é obrigatória!.
        /// </summary>
        public static string VAL004 {
            get {
                return ResourceManager.GetString("VAL004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Os cambos de {0} não conferem!.
        /// </summary>
        public static string VAL005 {
            get {
                return ResourceManager.GetString("VAL005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Insira um {0} válido!.
        /// </summary>
        public static string VAL006 {
            get {
                return ResourceManager.GetString("VAL006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * O {0} deve estar entre {1} e {2}!.
        /// </summary>
        public static string VAL007 {
            get {
                return ResourceManager.GetString("VAL007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * A {0} deve ter no mínimo {2} e máximo {1} caracteres!.
        /// </summary>
        public static string VAL008 {
            get {
                return ResourceManager.GetString("VAL008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Insira sua {0}!.
        /// </summary>
        public static string VAL009 {
            get {
                return ResourceManager.GetString("VAL009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Insira seu {0}!.
        /// </summary>
        public static string VAL010 {
            get {
                return ResourceManager.GetString("VAL010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * O {0} é obrigatória!.
        /// </summary>
        public static string VAL011 {
            get {
                return ResourceManager.GetString("VAL011", resourceCulture);
            }
        }
    }
}
